#!/usr/bin/env python3
"""
Generates blaster_pcm.h, the shot sound played on the on-board ES8311 codec.

Physical model rather than a plain descending beep. The Star Wars blaster was
recorded by striking the guy-wire of a radio tower, and a steel cable is a
DISPERSIVE waveguide: high frequencies travel faster than low ones. Each time
the wave reflects off the far end it comes back smeared, highs first - which is
what makes the "pew" sweep downwards, and it repeats on every round trip.

That is modelled here as a Karplus-Strong delay loop whose feedback path is a
chain of allpass sections (frequency-dependent delay = dispersion) plus a
one-pole lowpass (the cable damps highs faster than lows).

This is a synthesis, NOT the film's audio, which is a copyrighted sound effect.

The samples are compiled into the firmware (no SD card on this board), so the
rate is kept low on purpose: 16 kHz mono is ~14 kB of flash for 0.45 s.

Usage:  python3 tools/make_blaster.py [--wav preview.wav]

The firmware now ships recorded shots (tools/wav_to_blaster.py); this synthesis stays as a fallback.
"""

import argparse
import wave

import numpy as np

SAMPLE_RATE = 16000        # must match AUDIO_SAMPLE_RATE in config.h
DURATION_S = 0.35
PEAK = 0.99                # the codec clips above this, the limiter below keeps us under

# The "cable". Two strings of different length: a real guy-wire rings on several
# modes at once, and the beating between them gives the shot its body.
STRINGS = (
    # delay, allpass sections, allpass coeff, damping, feedback, level
    # Short delays on purpose: delay 12 @ 16 kHz = 1.3 kHz, and the dispersion drags the
    # sweep down from there. A small 8 ohm speaker has no output below ~400 Hz, so a
    # longer "cable" puts all the energy where nothing can radiate it.
    (12, 10, 0.78, 0.12, 0.9988, 1.00),
    (17,  8, 0.74, 0.16, 0.9980, 0.55),
)
HIGHPASS_HZ = 350          # everything below is wasted headroom on this speaker
STRIKE_TAU_S = 0.0025      # the hammer blow exciting the cable
DRIVE = 6.5                # soft-clipping gain: a blaster decays fast, so raising the
                           # average level matters far more than the peak for loudness


def dispersive_string(excite, delay_len, n_allpass, allpass_a, damping, feedback):
    """One round trip of the wave along the cable, over and over."""
    buf = np.zeros(delay_len)
    ap_state = np.zeros(n_allpass)
    out = np.zeros(len(excite))
    lowpass = 0.0
    idx = 0
    for i in range(len(excite)):
        v = buf[idx]
        for k in range(n_allpass):                 # dispersion: highs come back first
            y = allpass_a * v + ap_state[k]
            ap_state[k] = v - allpass_a * y
            v = y
        lowpass = (1.0 - damping) * v + damping * lowpass   # the cable eats the highs
        v = lowpass
        s = excite[i] + feedback * v
        buf[idx] = s
        out[i] = s
        idx = (idx + 1) % delay_len
    return out


def blaster():
    n = int(SAMPLE_RATE * DURATION_S)
    t = np.arange(n) / SAMPLE_RATE

    # The strike: a very short noise burst is what a hammer blow looks like
    rng = np.random.default_rng(1977)
    excite = rng.standard_normal(n) * np.exp(-t / STRIKE_TAU_S)

    signal = np.zeros(n)
    for delay, n_ap, a, damp, fb, level in STRINGS:
        signal += level * dispersive_string(excite, delay, n_ap, a, damp, fb)

    # Keep a touch of the raw strike so the shot still has a crack on the attack
    signal += 0.25 * excite

    # One-pole highpass: drop what the speaker cannot radiate, so the normalisation
    # below spends the full scale on the audible band instead of on inaudible bass.
    rc = 1.0 / (2 * np.pi * HIGHPASS_HZ)
    alpha = rc / (rc + 1.0 / SAMPLE_RATE)
    hp = np.empty_like(signal)
    hp[0] = signal[0]
    for i in range(1, len(signal)):
        hp[i] = alpha * (hp[i - 1] + signal[i] - signal[i - 1])
    signal = hp

    # Fade the last 10 ms so the speaker does not click
    tail = int(SAMPLE_RATE * 0.01)
    signal[-tail:] *= np.linspace(1.0, 0.0, tail)

    signal /= np.max(np.abs(signal))

    # Soft clipping: raises the RMS by ~10 dB without ever going over full scale, and the
    # added harmonics give the shot its grit. tanh saturates smoothly, so no digital crackle.
    signal = np.tanh(DRIVE * signal) / np.tanh(DRIVE)

    signal /= np.max(np.abs(signal))
    return (signal * PEAK * 32767).astype("<i2")


def write_header(samples, path):
    with open(path, "w") as out:
        out.write("#pragma once\n#include <Arduino.h>\n\n")
        out.write("/* Generated by tools/make_blaster.py - do not edit by hand. */\n\n")
        out.write(f"#define BLASTER_PCM_RATE    {SAMPLE_RATE}\n")
        out.write(f"#define BLASTER_PCM_SAMPLES {len(samples)}\n")
        out.write("#define BLASTER_SHOT_COUNT  1\n\n")
        out.write("static const uint32_t BLASTER_SHOT_START[BLASTER_SHOT_COUNT] = { 0 };\n")
        out.write(f"static const uint32_t BLASTER_SHOT_LEN[BLASTER_SHOT_COUNT]   = {{ {len(samples)} }};\n\n")
        out.write("static const int16_t BLASTER_PCM[BLASTER_PCM_SAMPLES] = {\n")
        for i in range(0, len(samples), 12):
            row = ", ".join(f"{v:6d}" for v in samples[i:i + 12])
            out.write(f"    {row},\n")
        out.write("};\n")
    print(f"{path}: {len(samples)} samples, {len(samples) * 2} bytes of flash, "
          f"{len(samples) / SAMPLE_RATE:.2f} s @ {SAMPLE_RATE} Hz")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="blaster_pcm.h")
    ap.add_argument("--wav", help="also write a WAV to listen to the result on a PC")
    args = ap.parse_args()

    samples = blaster()
    write_header(samples, args.out)
    if args.wav:
        with wave.open(args.wav, "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(SAMPLE_RATE)
            w.writeframes(samples.tobytes())
        print(f"{args.wav}: preview written")


if __name__ == "__main__":
    main()
