#!/usr/bin/env python3
"""
Converts a recorded blaster WAV into blaster_pcm.h, the shot sounds played on the ES8311 codec.

The source may hold several shots separated by silence (a sound-bank file usually does):
they are cut apart, the strongest --shots ones are kept, and the firmware plays a different
one at each shot so a salvo does not sound like a loop.

Processing per shot: mono mix, anti-alias lowpass + resampling to 16 kHz (AUDIO_SAMPLE_RATE),
highpass at --highpass Hz (a small 8 ohm speaker radiates nothing below, it only eats headroom),
trim from just before the onset to where it has decayed by 40 dB (capped at --max-ms),
short fades, then the same peak for every shot, with an optional soft saturation (--drive)
that raises the perceived loudness of a sound that decays this fast.

numpy only (no scipy). Usage:
  python3 tools/wav_to_blaster.py ~/Téléchargements/shot.wav --out blaster_pcm.h --wav /tmp/preview.wav
"""

import argparse
import os
import wave

import numpy as np

SAMPLE_RATE = 16000        # must match AUDIO_SAMPLE_RATE in config.h
PEAK = 0.97


def read_wav(path):
    with wave.open(path, "rb") as w:
        rate, ch, width, n = w.getframerate(), w.getnchannels(), w.getsampwidth(), w.getnframes()
        raw = w.readframes(n)
    if width == 2:
        x = np.frombuffer(raw, "<i2").astype(np.float64) / 32768.0
    elif width == 3:
        b = np.frombuffer(raw, np.uint8).reshape(-1, 3)
        x = ((b[:, 0].astype(np.int32) | (b[:, 1].astype(np.int32) << 8) | (b[:, 2].astype(np.int32) << 16)) << 8 >> 8) / 8388608.0
    elif width == 1:
        x = (np.frombuffer(raw, np.uint8).astype(np.float64) - 128.0) / 128.0
    else:
        raise SystemExit(f"unsupported sample width {width}")
    return x.reshape(-1, ch).mean(axis=1), rate


def lowpass_fir(cutoff, rate, taps=255):
    """Windowed-sinc lowpass, cutoff in Hz."""
    m = np.arange(taps) - (taps - 1) / 2
    h = np.sinc(2 * cutoff / rate * m) * np.blackman(taps)
    return h / h.sum()


def resample(x, src, dst):
    if src == dst:
        return x
    x = np.convolve(x, lowpass_fir(0.45 * min(src, dst), src), mode="same")
    if src % dst == 0:
        return x[:: src // dst]
    t = np.arange(int(len(x) * dst / src)) * src / dst
    return np.interp(t, np.arange(len(x)), x)


def highpass(x, hz, rate):
    if hz <= 0:
        return x
    rc = 1.0 / (2 * np.pi * hz)
    a = rc / (rc + 1.0 / rate)
    y = np.empty_like(x)
    y[0] = x[0]
    for i in range(1, len(x)):
        y[i] = a * (y[i - 1] + x[i] - x[i - 1])
    return y


def envelope(x, rate, win_ms=5):
    w = max(1, int(rate * win_ms / 1000))
    pad = np.concatenate([np.abs(x), np.zeros(w)])
    return np.array([pad[i:i + w].max() for i in range(0, len(x), w)]), w


def split_shots(x, rate, max_ms):
    """Onsets = envelope above 10 % of the file peak after >= 100 ms of quiet."""
    env, w = envelope(x, rate)
    thr = 0.10 * env.max()
    quiet_blocks = int(0.1 * rate / w)
    shots, i, quiet = [], 0, quiet_blocks
    while i < len(env):
        if env[i] < thr:
            quiet += 1
            i += 1
            continue
        if quiet < quiet_blocks:
            i += 1
            quiet = 0
            continue
        start_blk = max(0, i - 1)                   # keep ~5 ms before the attack
        peak = env[i:i + int(0.1 * rate / w)].max()
        end_blk = i
        limit = min(len(env), i + int(max_ms / 1000 * rate / w))
        while end_blk < limit and env[end_blk] > peak * 0.01:   # -40 dB
            end_blk += 1
        shots.append((start_blk * w, min(len(x), end_blk * w)))
        i, quiet = end_blk, 0
    return shots


def shape(seg, rate, drive):
    fade_in, fade_out = int(rate * 0.001), int(rate * 0.02)
    seg = seg.copy()
    seg[:fade_in] *= np.linspace(0, 1, fade_in)
    seg[-fade_out:] *= np.linspace(1, 0, fade_out)
    seg /= np.max(np.abs(seg))
    if drive > 0:
        seg = np.tanh(drive * seg) / np.tanh(drive)
    return (seg / np.max(np.abs(seg)) * PEAK * 32767).astype("<i2")


def write_header(shots, path, source):
    pcm = np.concatenate(shots)
    starts = np.cumsum([0] + [len(s) for s in shots[:-1]])
    with open(path, "w") as out:
        out.write("#pragma once\n#include <Arduino.h>\n\n")
        out.write(f"/* Generated by tools/wav_to_blaster.py from {source} - do not edit by hand. */\n\n")
        out.write(f"#define BLASTER_PCM_RATE    {SAMPLE_RATE}\n")
        out.write(f"#define BLASTER_PCM_SAMPLES {len(pcm)}\n")
        out.write(f"#define BLASTER_SHOT_COUNT  {len(shots)}\n\n")
        out.write("static const uint32_t BLASTER_SHOT_START[BLASTER_SHOT_COUNT] = { "
                  + ", ".join(str(int(v)) for v in starts) + " };\n")
        out.write("static const uint32_t BLASTER_SHOT_LEN[BLASTER_SHOT_COUNT]   = { "
                  + ", ".join(str(len(s)) for s in shots) + " };\n\n")
        out.write("static const int16_t BLASTER_PCM[BLASTER_PCM_SAMPLES] = {\n")
        for i in range(0, len(pcm), 12):
            out.write("    " + ", ".join(f"{v:6d}" for v in pcm[i:i + 12]) + ",\n")
        out.write("};\n")
    print(f"{path}: {len(shots)} shots, {len(pcm)} samples, {len(pcm) * 2} bytes of flash @ {SAMPLE_RATE} Hz")
    return pcm


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src", help="source WAV (8/16/24-bit PCM, any rate, mono or stereo)")
    ap.add_argument("--out", default="blaster_pcm.h")
    ap.add_argument("--wav", help="also write the kept shots as a WAV preview")
    ap.add_argument("--shots", type=int, default=4, help="how many shots to keep (strongest first)")
    ap.add_argument("--max-ms", type=int, default=450, help="longest shot kept")
    ap.add_argument("--highpass", type=float, default=250.0)
    ap.add_argument("--drive", type=float, default=2.0, help="soft saturation, 0 = none")
    args = ap.parse_args()

    x, rate = read_wav(args.src)
    x = highpass(resample(x, rate, SAMPLE_RATE), args.highpass, SAMPLE_RATE)
    found = split_shots(x, SAMPLE_RATE, args.max_ms)
    if not found:
        raise SystemExit("no shot found in the file")
    # Strongest first by energy, then back to file order
    ranked = sorted(found, key=lambda se: -np.sum(x[se[0]:se[1]] ** 2))[: args.shots]
    ranked.sort()
    for s, e in ranked:
        print(f"  shot at {s / SAMPLE_RATE:6.2f} s, {1000 * (e - s) / SAMPLE_RATE:4.0f} ms")
    print(f"{len(found)} shots found, {len(ranked)} kept")

    shots = [shape(x[s:e], SAMPLE_RATE, args.drive) for s, e in ranked]
    pcm = write_header(shots, args.out, os.path.basename(args.src))
    if args.wav:
        gap = np.zeros(int(0.3 * SAMPLE_RATE), "<i2")
        with wave.open(args.wav, "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(SAMPLE_RATE)
            w.writeframes(np.concatenate([np.concatenate([s, gap]) for s in shots]).tobytes())
        print(f"{args.wav}: preview written")


if __name__ == "__main__":
    main()
